# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 20
  # - name: Skills
  #   url: '#skills'
  #   weight: 40
  # - name: Experience
  #   url: '#experience'
  #   weight: 50
  # - name: Accomplishments
  #   url: '#accomplishments'
  #   weight: 60
  - name: Projects
    url: '#projects'
    weight: 70
  # - name: Featured
  #   url: '#featured'
  #   weight: 80
  - name: Publications
    url: '#publications'
    weight: 90
  # - name: Posts
  #   url: '#posts'
    # weight: 100
  - name: Contact
    url: '#contact'
    weight: 140

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  # - name: CV
  #   url: 'https://cv.songshgeo.com/uploads/SongshGeo_CV.pdf'
  #   weight: 70
  - name: GitHub
    url: '#skills'
    weight: 120
  - name: Blog (non-academic)
    url: 'https://songshgeo.com/'
    weight: 130
